import { PrismaClient, UserRole, UserRank } from '@prisma/client';

export const seedUsers = async (prisma: PrismaClient) => {
  await prisma.user.createMany({
    data: [
      {
        id: 'user-1',
        email: 'alice@example.com',
        nickname: '총명한판다',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-2',
        email: 'bob@example.com',
        nickname: '코딩하는너굴',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-3',
        email: 'charlie@example.com',
        nickname: '개발자뚱이',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.EXPERT,
      },
      {
        id: 'user-4',
        email: 'dana@example.com',
        nickname: '리액트냥이',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-5',
        email: 'edward@example.com',
        nickname: '프론트곰돌이',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.EXPERT,
      },
      {
        id: 'user-6',
        email: 'frank@example.com',
        nickname: '백엔드돌고래',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-7',
        email: 'grace@example.com',
        nickname: 'JS스폰지밥',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-8',
        email: 'harry@example.com',
        nickname: '타입짱냥이',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.EXPERT,
      },
      {
        id: 'user-9',
        email: 'isla@example.com',
        nickname: '태일윈드너구리',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-10',
        email: 'jack@example.com',
        nickname: '깃허브정령',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-11',
        email: 'kate@example.com',
        nickname: '미들웨어쫀득이',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.EXPERT,
      },
      {
        id: 'user-12',
        email: 'leo@example.com',
        nickname: 'REST정복자',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-13',
        email: 'mina@example.com',
        nickname: '리눅스사슴',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
      {
        id: 'user-14',
        email: 'nate@example.com',
        nickname: 'DB마스터호랑이',
        password: 'hashed-password',
        role: UserRole.ADMIN,
        rank: UserRank.EXPERT,
      },
      {
        id: 'user-15',
        email: 'olivia@example.com',
        nickname: '소켓챗봇여왕',
        password: 'hashed-password',
        role: UserRole.USER,
        rank: UserRank.NORMAL,
      },
    ],
    skipDuplicates: true,
  });

  console.log('✅ Users 15명 생성 완료!');
};
